[toolchain]

[features]
resolution = true
skip-lint = false

[programs.mainnet]
trash = "BgFw4NEPdqsQkjDqtH2Qbb1aSxK41f95HoRTKJXfMW3x"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/mainnet-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
